### PR TITLE
Step 2 & 3 - complete architectural improvements

### PR DESCRIPTION
**Pull request by julichan**
Hello,
Here is a large server update:

- Convertion from CIJ to ES6 to make the app code more modern.
- Multi-database support architecture (I thought i could add mariadb and postgres later).
- Extracted most of the logic that shouldn't be in the databases stores.
- Improved plugin and server setup handling (plus new initilization methods for later).
- Improved the objects architectures with helpers and logics folders. This imply a cleanup of files that were not really placed correctly. The two different folder have one major difference: the helpers are autonomous and only depends of other helpers and external modules while the logics folders depends solely on internal code and database store.
- Initialization and finalization logs.
- Dependencies overall updates!
- A fix on hidden errors.
- A fix on database life cycle to avoid potential corruption.
- Two fixes related to background upload possible malfunction (when the file already exists and when the insertion in database fails)
- **Added database files that were missing in the last Pull request**
- Updated .gitignore and .dockerignore

A small frontend update:

- Dependencies updates
- A typo in bookmark edition button (Edit => Save)
- Changed some routes to match server updates.

A small build update:

- Dependencies updates
- Node image update

This is a large enough PR so I did not change any logic. 
Note: that I tested user features but it's possible i still missed something and introduced a bug or two.

New logging system sample:
image

### CODE REVIEW

**Comment by julichan** [comment]
This pull request includes the previous pull request and further changes i had planned to send you once your merged the first one.
Since it was a new branch based on the older one, i deleted the older pull request.

My comment in reply to yours about starting the multi user development has been deleted alongside the other PR so I'm reiterating it here in case you missed it:

I think you should merge this and discuss about the multi user development. This makes it easier to make the multi user feature but there is a bunch of improvement I think that should still be made for that new feature.
- I'm planning to introduce a request context system, it'll drastically simplify the user logics as the user data will be available at every request without making the request agains
- I'm planning to introduce a task scheduled system to performs task periodically such as cleaning the database or updating the links automatically
- I think the UUID system drastically complexify the development of the multi user features so I'm proposing the following:
  - The browser local storage should only be used in nologin mode and it will not synchronised with a default user.
  - Replace the uuid everywhere with user id. 
  - By default have a user with id 0 which server a user for the nologin mode. This user settings could be used as default settings for new session or new users. in multi-user mode, all objets linked to it could be used to share dashboards and links but only admin can modify them.
  - In multi user mode, we should stricly used the server user settings and forget the browser local storage so an user can have his settings synchronised accross browsers and machines and there would be no need for the Sync button.
  
 This is just a proposal. Do you agree or oppose this ? do you have a different idea ?

**Comment by AlexSciFier** [comment]
Still can't run the server
```
npm run dev
> neonlink-backend@1.0.0 start
> fastify start -a "0.0.0.0" -l info --body-limit 5242880 app.js

Error: D:\Dev\neonlink-fork\neonlink\server\app.js doesn't exist within D:\Dev\neonlink-fork\neonlink\server
```

**Comment by AlexSciFier** [comment]
Runing with `node .\server.js` gives another error
```
❯ node .\server.js
Debugger attached.
Database plugin initialization completed.
Host plugin initialization completed.
{"level":40,"time":1688711743953,"pid":8516,"hostname":"DESKTOP-A02GGPK","msg":"\"root\" path \"D:\\Dev\\neonlink-fork\\neonlink\\server\\public\" must exist"}
Life cycle plugin initialization completed.
Starting migrations...
Applying initial database script...
Attempt to apply initial...
TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "db\sqlite\migrations\initial.sql" is not a valid package name imported from D:\Dev\neonlink-fork\neonlink\server\db\sqlite\database.js
    at new NodeError (node:internal/errors:399:5)
    at parsePackageName (node:internal/modules/esm/resolve:817:11)
    at packageResolve (node:internal/modules/esm/resolve:840:5)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```

**Comment by AlexSciFier** [comment]
Also `/server/data` direcory doesnt exist. Maybe create it on startup?

**Comment by AlexSciFier** [comment]
About TypeSctipt. Yes this would be great, at least for server side.

**Comment by julichan** [comment]
> Still can't run the server
> 
> ```
> npm run dev
> > neonlink-backend@1.0.0 start
> > fastify start -a "0.0.0.0" -l info --body-limit 5242880 app.js
> 
> Error: D:\Dev\neonlink-fork\neonlink\server\app.js doesn't exist within D:\Dev\neonlink-fork\neonlink\server
> ```

I've been usong the docker image and it picked server.js. app.js was a dependency of server.js before but i can rename the file if you want.

> Runing with `node .\server.js` gives another error
> 
> ```
> ❯ node .\server.js
> Debugger attached.
> Database plugin initialization completed.
> Host plugin initialization completed.
> {"level":40,"time":1688711743953,"pid":8516,"hostname":"DESKTOP-A02GGPK","msg":"\"root\" path \"D:\\Dev\\neonlink-fork\\neonlink\\server\\public\" must exist"}
> Life cycle plugin initialization completed.
> Starting migrations...
> Applying initial database script...
> Attempt to apply initial...
> TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "db\sqlite\migrations\initial.sql" is not a valid package name imported from D:\Dev\neonlink-fork\neonlink\server\db\sqlite\database.js
>     at new NodeError (node:internal/errors:399:5)
>     at parsePackageName (node:internal/modules/esm/resolve:817:11)
>     at packageResolve (node:internal/modules/esm/resolve:840:5)
>     at moduleResolve (node:internal/modules/esm/resolve:938:20)
>     at defaultResolve (node:internal/modules/esm/resolve:1153:11)
>     at nextResolve (node:internal/modules/esm/loader:163:28)
>     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
>     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
>     at ESMLoader.import (node:internal/modules/esm/loader:525:22)
>     at importModuleDynamically (node:internal/modules/esm/translators:110:35) {
>   code: 'ERR_INVALID_MODULE_SPECIFIER'
> }
> ```

That s a run without a database outside docker, i'll try it and fix it.

> Also `/server/data` direcory doesnt exist. Maybe create it on startup?

I had this one mounted by my dockerfile so gotcha i'll add folder creation in the initialization.

You'll have a the fixes sometimes today.

**Comment by AlexSciFier** [comment]
> I've been usong the docker image and it picked server.js. app.js was a dependency of server.js before but i can rename the file if you want.

Yes, please.

**Comment by julichan** [comment]
alright, you can try again. the database part seems to work on my windows without docker without breaking the docker/linux side.

**Comment by AlexSciFier** [comment]
It seems that @fastify/sensible didn't work properly. Is always return 500.
For ex.: When i request /api/user/me with empty user table it shoud respond with 404 code, instead it return 500

**Comment by julichan** [comment]
This is how i set it up. I can change that.

**Comment by julichan** [comment]
Done

**Comment by julichan** [comment]
Are your tests going well?

**Comment by AlexSciFier** [comment]
Added [fastify-cli](https://github.com/fastify/fastify-cli) for development and prettier for code format. There is few bugs that i found.

**Comment by AlexSciFier** [comment]
Error loading file with bookmarks
image

```
{"level":50,"time":1688748192353,"pid":1,"hostname":"36d456e9799a","reqId":"req-l","req":{"method":"POST","url":"/api/utils/parseBookmarkFile","hostname":"localhost","remoteAddress":"172.19.0.1","remotePort":43690},"res":{"statusCode":500},"err":{"type":"TypeError","message":"Cannot read properties of undefined (reading 'file')","stack":"TypeError: Cannot read properties of undefined (reading 'file')\n    at Object.<anonymous> (file:///app/routes/api/utils/index.js:40:44)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:139:37)\n    at validationCompleted (/app/node_modules/fastify/lib/handleRequest.js:123:5)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:99:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:76:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:192:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:186:14)\n    at Parser.setMultipart [as fn] (/app/node_modules/@fastify/multipart/index.js:35:3)\n    at ContentTypeParser.run (/app/node_modules/fastify/lib/contentTypeParser.js:177:27)"},"msg":"Cannot read properties of undefined (reading 'file')"}
```

**Comment by julichan** [comment]
I found another bug along side the bookmarks import bug: the bookmarks update.
Both are fixed.

**Comment by julichan** [comment]
The force push was to remove a cleanup commit that partially undid prettification on one file. I recommited correct changes afterwards.

**Comment by julichan** [comment]
I yave a little question. Your commit of with fastify-cli tenamed app.js into server.js and recreated another app.js which doesn't seem used. Is it to start the app with fastify-cli instead?

**Comment by AlexSciFier** [comment]
Fastify-cli uses app.js to run in a dev mode (see the "dev" script in package.json). server.js is needed to run this app in production, because fastify-cli is a dev dependency.

**Pull request merged**
